config/routes.rb
Rails.application.routes.draw do
  resources :play_backs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#index'

  post 'count', to: 'counters#count'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play_back.rb
class PlayBack < ApplicationRecord
  mount_uploader :video, VideoUploader
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :play_backs, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :check_owner

  def check_owner
    redirect_to play_backs_path,
    alert: t(:oops_401).capitalize if @play_back.user.id != current_user.id
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  protect_from_forgery except: [:count]
  def count
    @video_id = counter_params[:v_id]
    @video_view = counter_params[:view]
    update_video_views
  end

  def update_video_views
    @play_back = PlayBack.find(@video_id)
    @views_old = @play_back.views

    render status: :ok, json: { message: 'all fine' }.to_json if update_views
  end

  def counter_params
    params.require(:counter).permit(:v_id, :view)
  end

  def update_views
    @play_back.update(views: (@views_old + 1)) && @video_view
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!, only: %i[index]
  def index
    redirect_to play_backs_path if signed_in?
  end
end

app/controllers/play_backs_controller.rb
class PlayBacksController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :set_play_back, only: %i[show edit update destroy]
  before_action :check_owner, only: %i[edit update destroy]

  # GET /play_backs
  # GET /play_backs.json
  def index
    @user = User.find(current_user.id)
    @play_backs = @user.play_backs
  end

  # GET /play_backs/1
  # GET /play_backs/1.json
  def show
  end

  # GET /play_backs/new
  def new
    @play_back = PlayBack.new
  end

  # GET /play_backs/1/edit
  def edit
  end

  # POST /play_backs
  # POST /play_backs.json
  def create
    @play_back = PlayBack.new(play_back_params)
    if try_saving
      redirect_to @play_back, notice: "#{t(:play_back)} #{t(:created)}."
    else
      flash.now[:alert] = t(:oops_error)
      render :new
    end
  end

  # PATCH/PUT /play_backs/1
  # PATCH/PUT /play_backs/1.json
  def update
    if @play_back.update(play_back_params)
      redirect_to @play_back, notice: "#{t(:play_back)} #{t(:updated)}."
    else
      render :edit
    end
  end

  # DELETE /play_backs/1
  # DELETE /play_backs/1.json
  def destroy
    @play_back.destroy
    erase_data
    redirect_to play_backs_url, notice: "#{t(:play_back)} #{t(:destroyed)}."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_play_back
    @play_back = PlayBack.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def play_back_params
    params.require(:play_back)
          .permit(:title, :video)
          .merge(url: exist_play_back ? @play_back.url : 'link',
                 views: exist_play_back ? @play_back.views : 0,
                 user_id: current_user.id)
  end
  # rubocop:disable all
  def generate_m3u8
    require 'm3u8'
    require 'tempfile'
    require 'fileutils'

    absolute_path = request.original_url
    video_path = File.join 'uploads', 'play_back', 'video', @play_back.id.to_s
    path = File.join Rails.root, 'public', 'uploads', 'play_back',
                                 'video', @play_back.id.to_s
    FileUtils.mkdir_p(path) unless File.exist?(path)

    @address = @play_back.video_url.to_s.split('/')
    name = @address.pop

    in_= "#{path}/#{name}"
    out_ = "#{in_}.m3u8"
    ffmpeg = "ffmpeg -i #{in_} -hls_time 20 -hls_flags single_file #{out_}"

    unless (File.exist?(in_))
      FileUtils.mv("#{Rails.root}/public#{@play_back.video_url.to_s}", in_)
    end
    unless (File.exist?("#{in_}.m3u8"))
      system(ffmpeg)
    end
    
    master_playlist = M3u8::Playlist.new
    options = { level: 4.1, audio_codec: 'aac-lc', bandwidth: 540,
                uri: "#{request.base_url}/#{video_path}/#{name}.m3u8" }
    item = M3u8::PlaylistItem.new(options)
    master_playlist.items << item
    File.write("#{path}/master_#{name}.m3u8", "#{master_playlist.to_s}")

    new_url = "#{request.base_url}/#{video_path}/master_#{name}.m3u8"
    @play_back.update(url: new_url)
  end
  # rubocop:enable all

  def try_saving
    !params[:play_back][:video].nil? && @play_back.save && generate_m3u8
  end

  def exist_play_back
    !@play_back.nil? && @play_back.persisted?
  end

  def erase_data
    require 'fileutils'

    prefix = request.base_url
    suffix = @play_back.url.split('/').pop
    dir = @play_back.url.delete_suffix(suffix)
    dir = dir.delete_prefix(prefix)
    FileUtils.rm_rf("public#{dir}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/play_backs_helper.rb
module PlayBacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videostructure</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
    <div class="alert alert-secondary" role="alert">
      <%= notice %>
    </div>
      <!--<p class="notice"><%= notice %></p>-->
    <% end %>
    <% if flash[:alert]%>
    <div class="alert alert-secondary" role="alert">
      <%= alert %>
    </div>
      <!--<p class="alert"><%= alert %></p>-->
    <% end %>

    <%= render 'shared/header' if signed_in? %>

    <div class="container">
      <div class="row justify-content-sm-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="col col-lg-8">
  <h1><%= t(:video_structure_main_title).capitalize %></h1>
  <h4><%= t(:welcome_message).capitalize %></h4>
  <!--<marquee><%= t(:wip).capitalize %></marquee>-->
  <div class="row justify-content-around">
    <h6>
        <%= link_to t(:enter).capitalize , new_user_session_path, class:'btn btn-lg btn-info' %>
    </h6>
    <h6>
        <%= link_to t(:create_account).capitalize , new_user_registration_path, class:'btn btn-lg btn-info' %>
    </h6>
  </div>
</div>

app/views/play_backs/_form.html.erb
<%= form_with(model: play_back, local: true) do |form| %>
  <% if play_back.errors.any? %>
    <div id='error_explanation'>
      <ul>
        <% play_back.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field custom_field'>
    <%= form.label :title, t(:title).capitalize %>
    <%= form.text_field :title %>
  </div>

  <div class='field custom_field'>
    <%= form.label :video, t(:upload_type_message).capitalize %>
    <%= form.file_field :video%>
  </div>

  <div class='actions custom_field'>
    <%= form.submit t(:save).capitalize %>
  </div>
<% end %>

app/views/play_backs/edit.html.erb
<div>
    <h2>Editing Play Back</h2>

    <%= render 'form', play_back: @play_back %>

    <%= link_to t(:show).capitalize, @play_back, class:'btn btn-info custom_btn_sm_no_h_margin' %>
    <%= link_to t(:back).capitalize, play_backs_path, class:'btn btn-info custom_btn_sm_no_h_margin' %>
</div>

app/views/play_backs/index.html.erb
<div class="justify-content-around">
  <h2><%= t(:play_backs).capitalize %></h2>

  <p>
    <%= link_to "#{t(:new).capitalize} #{t(:play_back).capitalize}", new_play_back_path, class:'btn btn-info custom_btn' %>
  </p>

  <table>
    <thead>
      <tr>
        <th><%= t(:title).capitalize %></th>
        <th><%= t(:url).capitalize %></th>
        <th><%= t(:views).capitalize %></th>
        <th colspan='3'></th>
      </tr>
    </thead>

    <tbody>
      <% @play_backs.each do |play_back| %>
        <tr>
          <td><%= play_back.title %></td>
          <td><%= play_back.url.truncate(10) %></td>
          <td><%= play_back.views %></td>
          <td><%= link_to(play_back, class: "action_icons", data:{reason: 'view'}) do %> &#128065; <% end %></td>
          <td><%= link_to(edit_play_back_path(play_back), class: "action_icons", data:{reason: 'edit'}) do %>&#9997; <% end %></td>
          <td><%= link_to(play_back, method: :delete, data: { confirm: 'Are you sure?' }, class: "action_icons") do %> &#10060; <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/play_backs/new.html.erb
<div>
    <h2><%= t(:new).capitalize %> <%= t(:play_back).capitalize %>:</h2>

    <%= render 'form', play_back: @play_back %>

    <%= link_to t(:back).capitalize , play_backs_path, class:'btn btn-info custom_btn_sm_no_h_margin' %>
</div>

app/views/play_backs/show.html.erb
<div class="col justify-content-center">
<!-- VideoJs-->
<link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />
<!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

<!--<p id='notice'><%= notice %></p>-->

<p>
  <strong><%= t(:title).capitalize %>:</strong>
  <%= @play_back.title %>
</p>

<p>
  <!--counter proprieties, based on: https://github.com/filhodoto/videojs-counter-plugin-->
  <span id="video_id" style="display: none;"><%= @play_back.id %></span>
  <span id="counter_path" style="display: none;"><%= count_path %></span>

  <video
    id="my-video"
    class="video-js"
    data-setup='{ "controls": true, "autoplay": true, "preload": "auto" }'
  >
    <source src="<%= @play_back.url %>" type="application/x-mpegURL" />

  </video>

  <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
  <%= javascript_pack_tag "videojs_custom" , 'data-turbolinks-track': 'reload' %>
  
</p>

<p>
  <strong><%= t(:url).capitalize %>:</strong>
  <%= link_to @play_back.url.truncate(30), @play_back.url, class: 'custom_link'%>
  <% @play_back.url %>
</p>

<p>
  
  <% if @play_back.views > 0 %>
    <strong><%= t(:views).capitalize %>: </strong>
    <%= @play_back.views %> - (<%= Time.current.strftime("%d/%m/%Y %H:%M")%>)
  <% else%>
    <%= t(:posted_at).capitalize %> - (<%= Time.current.strftime("%d/%m/%Y %H:%M")%>)
  <% end %>
  
</p>

<% if signed_in? %>
  <% unless @play_back.user.id != current_user.id %>
    <%= link_to t(:edit).capitalize , edit_play_back_path(@play_back), class:'btn btn-info custom_btn_sm' %>
  <% end %>
  <%= link_to t(:back).capitalize , play_backs_path, class:'btn btn-info custom_btn_sm' %>
<% else %>
  <%= link_to t(:home).capitalize , root_path, class:'btn btn-info custom_btn_sm' %>
<% end %>
</div>

app/views/shared/_header.html.erb
<h1><%= I18n.t(:video_structure_main_title).capitalize %></h1>
<%= link_to t(:play_backs), play_backs_path, class:'btn btn-info custom_btn_sm' %>
<%= link_to t(:log_out).capitalize, destroy_user_session_path, method: :delete, class:'btn btn-info custom_btn_sm' %>
<hr>